// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: mstHVACCOM.nrx

[
  uuid(B491E8A1-16A1-4FDC-A4F5-15313C541987),
  version(1.0),
  helpstring("mstHVACCOM 1.0 Type Library"),
  custom(DE77BA64-517C-11D1-A2DA-0000F8773CE9, 134283886),
  custom(DE77BA63-517C-11D1-A2DA-0000F8773CE9, 2147483647),
  custom(DE77BA65-517C-11D1-A2DA-0000F8773CE9, "Created by MIDL version 8.01.0622 at Tue Jan 19 06:14:07 2038
")

]
library mstHVACCOMLib
{
    // TLib : Model Studio Objects 1.0 Type Library : {1AE1985C-5D87-4E89-8E67-068628FC3CD6}
    importlib("UnitsCSCom.nrx");
    // TLib : OdaX 21.8 (x64) Type Library : {0DFA2554-8A2B-44D0-BE8F-85EEB803AEE9}
    importlib("OdaX_csd.dll");
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    interface IPropsDiaWrap;
    interface ImstHVACPart;

    [
      odl,
      uuid(16A76BEF-8358-4908-8F3D-6B38AE8F27E5),
      helpstring("IPropsDiaWrap Interface"),
      dual,
      nonextensible,
      oleautomation
    ]
    interface IPropsDiaWrap : IUnknown {
    };

    [
      odl,
      uuid(7A136EF8-DC43-49B1-8DB8-751D5A823ECE),
      helpstring("ImstHVACPart Interface"),
      dual,
      nonextensible,
      oleautomation
    ]
    interface ImstHVACPart : IAcadEntity {
        [id(0x00000001), propget, helpstring("Данные объекта")]
        HRESULT Element([out, retval] IElement** pVal);
        [id(0x00000001), propput, helpstring("Данные объекта")]
        HRESULT Element([in] IElement* pVal);
        [id(0x00000002), propget, helpstring("Параметрические данные")]
        HRESULT ParametricData([out, retval] IElement** pVal);
        [id(0x00000002), propput, helpstring("Параметрические данные")]
        HRESULT ParametricData([in] IElement* pVal);
        [id(0x00000003), propget, helpstring("Положение объекта")]
        HRESULT UnitPosition([out, retval] VARIANT* pVal);
        [id(0x00000003), propput, helpstring("Положение объекта")]
        HRESULT UnitPosition([in] VARIANT pVal);
        [id(0x00000004), propget, helpstring("Наименование объекта")]
        HRESULT UnitName([out, retval] BSTR* pVal);
        [id(0x00000004), propput, helpstring("Наименование объекта")]
        HRESULT UnitName([in] BSTR pVal);
        [id(0x00000008), propget, helpstring("Наименование")]
        HRESULT Part_Name([out, retval] BSTR* pVal);
        [id(0x00000008), propput, helpstring("Наименование")]
        HRESULT Part_Name([in] BSTR pVal);
        [id(0x00000009), propget, helpstring("Обозначение (модель)")]
        HRESULT Part_Tag([out, retval] BSTR* pVal);
        [id(0x00000009), propput, helpstring("Обозначение (модель)")]
        HRESULT Part_Tag([in] BSTR pVal);
        [id(0x0000000a), propget, helpstring("Производитель")]
        HRESULT Part_Manufacturer([out, retval] BSTR* pVal);
        [id(0x0000000a), propput, helpstring("Производитель")]
        HRESULT Part_Manufacturer([in] BSTR pVal);
        [id(0x0000000b), propget, helpstring("Нормативный документ")]
        HRESULT Part_Standard([out, retval] BSTR* pVal);
        [id(0x0000000b), propput, helpstring("Нормативный документ")]
        HRESULT Part_Standard([in] BSTR pVal);
        [id(0x0000000c), propget, helpstring("Ссылочный чертеж")]
        HRESULT Part_Refdrawing([out, retval] BSTR* pVal);
        [id(0x0000000c), propput, helpstring("Ссылочный чертеж")]
        HRESULT Part_Refdrawing([in] BSTR pVal);
        [id(0x0000000d), propget, helpstring("Материал")]
        HRESULT Part_Material([out, retval] BSTR* pVal);
        [id(0x0000000d), propput, helpstring("Материал")]
        HRESULT Part_Material([in] BSTR pVal);
        [id(0x0000000e), propget, helpstring("Нормативный документ на материал")]
        HRESULT Part_Material_Standard([out, retval] BSTR* pVal);
        [id(0x0000000e), propput, helpstring("Нормативный документ на материал")]
        HRESULT Part_Material_Standard([in] BSTR pVal);
        [id(0x0000000f), propget, helpstring("Вес")]
        HRESULT Part_Weight([out, retval] BSTR* pVal);
        [id(0x0000000f), propput, helpstring("Вес")]
        HRESULT Part_Weight([in] BSTR pVal);
        [id(0x00000010), propget, helpstring("Примечания")]
        HRESULT Part_Comment([out, retval] BSTR* pVal);
        [id(0x00000010), propput, helpstring("Примечания")]
        HRESULT Part_Comment([in] BSTR pVal);
        [id(0x00000011), propget, helpstring("Группа изделий")]
        HRESULT Part_Group([out, retval] BSTR* pVal);
        [id(0x00000011), propput, helpstring("Группа изделий")]
        HRESULT Part_Group([in] BSTR pVal);
        [id(0x00000012), propget, helpstring("Тип изделия")]
        HRESULT Part_Type([out, retval] BSTR* pVal);
        [id(0x00000012), propput, helpstring("Тип изделия")]
        HRESULT Part_Type([in] BSTR pVal);
        [id(0x00000013), propget, helpstring("Код ОКП")]
        HRESULT Part_Reference([out, retval] BSTR* pVal);
        [id(0x00000013), propput, helpstring("Код ОКП")]
        HRESULT Part_Reference([in] BSTR pVal);
        [id(0x00000014), propget, helpstring("Вес нетто")]
        HRESULT Part_Weight_Netto([out, retval] BSTR* pVal);
        [id(0x00000014), propput, helpstring("Вес нетто")]
        HRESULT Part_Weight_Netto([in] BSTR pVal);
        [id(0x00000015), propget, helpstring("Вес бруто")]
        HRESULT Part_Weight_Bruto([out, retval] BSTR* pVal);
        [id(0x00000015), propput, helpstring("Вес бруто")]
        HRESULT Part_Weight_Bruto([in] BSTR pVal);
        [id(0x00000016), propget, helpstring("Включение в экспликацию")]
        HRESULT Explication_Include([out, retval] long* pVal);
        [id(0x00000016), propput, helpstring("Включение в экспликацию")]
        HRESULT Explication_Include([in] long pVal);
        [id(0x00000017), propget, helpstring("Позиция по экспликации")]
        HRESULT Explication_Number([out, retval] BSTR* pVal);
        [id(0x00000017), propput, helpstring("Позиция по экспликации")]
        HRESULT Explication_Number([in] BSTR pVal);
        [id(0x00000018), propget, helpstring("Группа по экспликации")]
        HRESULT Explication_Group([out, retval] BSTR* pVal);
        [id(0x00000018), propput, helpstring("Группа по экспликации")]
        HRESULT Explication_Group([in] BSTR pVal);
        [id(0x00000019), propget, helpstring("Примечания к экспликации")]
        HRESULT Explication_Comment([out, retval] BSTR* pVal);
        [id(0x00000019), propput, helpstring("Примечания к экспликации")]
        HRESULT Explication_Comment([in] BSTR pVal);
        [id(0x0000001a), propget, helpstring("Включение в спецификацию")]
        HRESULT Bom_Include([out, retval] long* pVal);
        [id(0x0000001a), propput, helpstring("Включение в спецификацию")]
        HRESULT Bom_Include([in] long pVal);
        [id(0x0000001b), propget, helpstring("Позиция по спецификации")]
        HRESULT Bom_Number([out, retval] BSTR* pVal);
        [id(0x0000001b), propput, helpstring("Позиция по спецификации")]
        HRESULT Bom_Number([in] BSTR pVal);
        [id(0x0000001c), propget, helpstring("Группа по спецификации")]
        HRESULT Bom_Group([out, retval] BSTR* pVal);
        [id(0x0000001c), propput, helpstring("Группа по спецификации")]
        HRESULT Bom_Group([in] BSTR pVal);
        [id(0x0000001d), propget, helpstring("Количество")]
        HRESULT Bom_Qty([out, retval] BSTR* pVal);
        [id(0x0000001d), propput, helpstring("Количество")]
        HRESULT Bom_Qty([in] BSTR pVal);
        [id(0x0000001e), propget, helpstring("Примечания к спецификации")]
        HRESULT Bom_Comment([out, retval] BSTR* pVal);
        [id(0x0000001e), propput, helpstring("Примечания к спецификации")]
        HRESULT Bom_Comment([in] BSTR pVal);
    };

    [
      uuid(979590EF-E6D6-4F08-99EE-4C08411D1987),
      helpstring("mstHVACPart Class")
    ]
    coclass mstHVACPart {
        [default] interface ImstHVACPart;
        [default, source] interface IAcadObjectEvents;
    };

    [
      uuid(12BD3718-6246-4FE1-A0CD-88A63B6A1987),
      helpstring("PropsDiaWrap Class")
    ]
    coclass PropsDiaWrap {
        [default] interface IPropsDiaWrap;
    };
};
